### ISSUE TITLE
URL Issue - Manual Test Fine

### ISSUE THREAD

**Issue by jvanderaa** [jeffkala/pyurlcheck#4]
I re-ran the tests. I'm getting a couple of failures. One consistently and the other one was an one time issue.

This showed up one time and not others. Maybe a retry issue?
```
[ASA for Vagrant](https://techbloc.net/archives/2360)  
```

This link is showing up consistently, yet works when I go to it manually.
```
[GNS3 DMVPN Intro](http://resources.intenseschool.com/gns3-lab-introduction-to-dmvpn/) 
```

**Comment by jeffkala** [comment]
Thanks for reporting it @jvanderaa , I need to get focused in the next few weeks to put some work into this.

**Comment by jeffkala** [comment]
@jvanderaa turns out it required me to set a user-agent in the headers.
